"""add unique constraint to model element index

Revision ID: 90a71278ba72
Revises: 904ad466ef8f
Create Date: 2026-07-25 21:50:39.635298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90a71278ba72'
down_revision: Union[str, Sequence[str], None] = '904ad466ef8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_system_git_path', 'model_element_index', ['system_id', 'git_path'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_system_git_path', 'model_element_index', type_='unique')
    # ### end Alembic commands ###
