"""add pr number to artifact versions

Revision ID: f34d8a319778
Revises: 90a71278ba72
Create Date: 2026-07-28 17:43:26.105571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f34d8a319778'
down_revision: Union[str, Sequence[str], None] = '90a71278ba72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifact_versions', sa.Column('pr_number', sa.Integer(), nullable=True))
    op.create_unique_constraint('uq_artifact_versions_system_run', 'artifact_versions', ['system_id', 'run_id'])
    op.create_unique_constraint(None, 'artifact_versions', ['pr_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artifact_versions', type_='unique')
    op.drop_constraint('uq_artifact_versions_system_run', 'artifact_versions', type_='unique')
    op.drop_column('artifact_versions', 'pr_number')
    # ### end Alembic commands ###
